name = "nano-bananary"
main = "_worker.js"
compatibility_date = "2024-09-09"

[build]
command = "npm run build"

[build.upload]
directory = "dist"

[env.production]
name = "nano-bananary"

# Environment variables can be set in Cloudflare dashboard or via wrangler CLI
# Example: wrangler secret put GEMINI_API_KEY
# [vars]
# ENVIRONMENT = "production"